[package]
name = "xcra"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
clap = { version = "4.5.20", features = ["derive"] }
handlebars = "6.2.0"
xcra_core = { path = "../xcra_core" }
serde.workspace = true
serde_json.workspace = true
